version: '3.7'

services:
  traefik:
    image: 'traefik:v2.0.1'
    container_name: 'traefik'
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - traefik
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
  nginx:
    image: nginx:alpine
    labels:
      - 'traefik.enable=true'
      # - 'traefik.frontend.rule=Host:nginx.docker.local'
      - 'traefik.port=80'
      - 'traefik.http.routers.nginx.rule=Host(`nginx.docker.localhost`)'
    volumes:
      - './website:/usr/share/nginx/html'
    networks:
      - traefik
networks:
  traefik:
    external: true
