version: "3"
services:

  db:
    image: oracle12c/ebx
    ports:
      - 1521:1521
      - 8088:8080
    volumes:
      - db-data:/u01/app/oracle
    networks:
      - backend

  wildfly:
    image:  wildfly/oracle
    environment:
      - DB_PORT=1521
    ports:
      - 8080:8080
      - 9990:9990
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data: