version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: 'ebx'
      POSTGRES_PASSWORD: 'ebx'
      POSTGRES_DB: 'ebxDatabase'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.nl
      PGADMIN_DEFAULT_PASSWORD: ebx
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    restart: unless-stopped

  wildfly:
    container_name: wildfly_ebx
    image: wildfly/postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ebxDatabase
      DB_USER: ebx
      DB_PWD: ebx
    volumes:
      - ./ebx:/opt/ebx/
      - ./deployments:/opt/wildfly/standalone/deployments/
    ports:
      - '9990:9990'
      - '8888:8080'
      - '8787:8787'
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
