## traefik.yml

# Docker configuration backend
providers:
    docker:
      exposedbydefault: true
  
  entryPoints:
    web:
      # Listen on port 80 for incoming requests
      address: :80
  
  # API and dashboard configuration
  api:
    insecure: true